replicacount: 3

image:
  name: mamathasama/javagithub
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: build-53
service:
  type: NodePort
  port: 8080

containerName: tomcat-webapp
namespace: production
labels:
  name: tomcat
  role: app
  tier: frontend
containerPort: 8080

