apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.labels.name }}
    role: {{ .Values.labels.role }}
    tier: {{ .Values.labels.tier }}
spec:
  type: {{ .Values.service.type }}
  selector:
    name: {{ .Values.labels.name }}
    role: {{ .Values.labels.role }}
    tier: {{ .Values.labels.tier }}
  ports:
  - port: {{ .Values.service.port }}
      
